export const GET_WEEKLY_TRACKS = "GET_WEEKLY_TRACKS";
export const GET_WEEKLY_ALBUMS = "GET_WEEKLY_ALBUMS";
export const GET_WEEKLY_ARTISTS = "GET_WEEKLY_ARTISTS";
export const GET_WEEKLY_RELEASES = "GET_WEEKLY_RELEASES";